# # How ~/.config/systemd/user/podman-hermes.service is generated
# - services.podman.containers.hermes = {}
# - <home-manager>/modules/services/podman-linux/containers.nix: services.podman.internal.quadletDefinitions
# - <home-manager>/modules/services/podman-linux/install-quadlet.nix: builtQuadlets = map buildPodmanQuadlet cfg.internal.quadletDefinitions;
#   - ${cfg.package}/lib/systemd/user-generators/podman-user-generator $out/units
#     Convert *.container (quadlet file) to *.service (systemd service file)
#
# # home-manager podman module Cons:
# - Need network-online.target, which is not request in nixos module.
# - It is hard to customize the StartExec as it is generated by podman-user-generator,
#   - E.g. I want to remove the -d (detach) arguments.
# - Systemd service is hard to debug. I can not directly run it like a script and inspect the output
#   - (which need journalctl, which is unnecessary abstraction)
{ pkgs, config, lib, ... }: let
  # TODO: use hermes from home.packages
  hermes-agent = (pkgs.flake-compat {src=pkgs.npinsed.ai.llm-agents;})
    .defaultNix.packages.${pkgs.stdenv.system}.hermes-agent;
  hermes-image = pkgs.dockerTools.buildImageWithNixDb {
    name = "hermes";
    tag = "latest";
    copyToRoot = pkgs.buildEnv {
      name = "root";
      paths = [
        pkgs.bashInteractive
        pkgs.cacert
        pkgs.coreutils
        pkgs.file
        pkgs.git
        pkgs.gnutar
        pkgs.nix
        pkgs.wget

        hermes-agent
        (pkgs.writeShellScriptBin "start-hermes" ''
          # init
          if [[ ! -d ~/.hermes ]]; then
            hermes setup --non-interactive
            hermes config set model.provider "kimi-coding"
            hermes config set model.base_url ${config.ai.kimi.api_endpoint};
            hermes config set model.default "kimi-for-coding"
          fi
          hermes gateway run
        '')
      ];
    };
  };
in {
  services.podman = {
    images.hermes = {
      # https://github.com/nix-community/home-manager/pull/6137
      image = "docker-archive:${hermes-image}";
      tag = "localhost/hermes:latest";
    };
    containers.hermes = let
      home-volume = "${config.home.homeDirectory}/.local/state/hermes-container";
    in {
      entrypoint = "/bin/start-hermes";
      environment = {
        HOME = "/root";
        KIMI_API_KEY = config.ai.kimi.api_key;
        MINIMAX_CN_API_KEY = config.ai.minimax-china.api_key;
        TAVILY_API_KEY = config.ai.tavily.api_key;
        DISCORD_BOT_TOKEN = lib.trim (builtins.readFile ~/Gist/Vault/AI/discord/yoga-hermes/bot-token.txt);
        GATEWAY_ALLOW_ALL_USERS=true;
        DISCORD_AUTO_THREAD=false;
        DISCORD_HOME_CHANNEL=lib.trim (builtins.readFile ~/Gist/Vault/AI/discord/yoga-hermes/home-channel.txt);
      };
      image = config.services.podman.images.hermes.tag;
      network = "host";
      volumes = [
        "${home-volume}:/root"
        "/nix:/nix:ro"
      ];
      extraConfig = {
        # See `man podman-systemd.unit`
        Service = {
          ExecStartPre="${pkgs.coreutils}/bin/mkdir -p ${home-volume}";
        };
      };
    };
  };
}
