theme: auto

server:
  address: tcp://127.0.0.1:9091/

log:
  level: info

authentication_backend:
  file:
    path: ./server/authelia/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: 127.0.0.1
      resources:
        - '^/app/.*$'
      policy: one_factor

session:
  cookies:
    - domain: 127.0.0.1
      authelia_url: https://127.0.0.1:8443
      default_redirection_url: https://127.0.0.1:8443/app/
      same_site: lax
      inactivity: 1h
      expiration: 1d
      remember_me: 1M

storage:
  local:
    # TODO: use home-manager's home
    path: /home/xieby1/.config/authelia/db.sqlite3

notifier:
  filesystem:
    # TODO: use home-manager's home
    filename: /home/xieby1/.config/authelia/notification.txt
