# Generated by hermes + opus 4.6
let
  pkgs = import <nixpkgs> {};
in pkgs.pkgsu.buildGoModule {
  name = "gomodel";
  src = pkgs.npinsed.ai.GoModel;
  vendorHash = "sha256-asthNpHYPZMxQ793LgZJPNFdsD2qzQu3OhAaQ/nPzrg=";
  postPatch = ''
    substituteInPlace go.mod --replace-fail "go 1.26.3" "go 1.26.1"
  '';
  # Build only the main binary
  subPackages = [ "cmd/gomodel" ];
}
